name: Sync Hugging Face Space to GitHub

on:
  workflow_dispatch: # Allows manual triggering
  schedule: # Optional: Set a schedule for periodic syncs
    - cron: '0 12 * * *' # Daily at 12:00 UTC

jobs:
  sync-space:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      # Step 2: Clone Hugging Face Space
      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/<your-hf-username>/<your-space-name> hf-space
          rsync -av --progress hf-space/ . --exclude .git

      # Step 3: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from Hugging Face Space" || echo "No changes to commit"
          git push
