name: Sync Hugging Face Space to GitHub

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule: # Set up a periodic sync schedule (optional)
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC

jobs:
  sync-space:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the GitHub repository
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      # Step 2: Clone the Hugging Face Space
      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/<therickglenn>/<MentalHealthDashboard> hf-space
          rsync -av --progress hf-space/ . --exclude .git

      # Step 3: Commit and Push Changes to GitHub
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions
